### ISSUE TITLE
Suggestion: Add meta tags

### ISSUE THREAD

**Issue by Lurku** [0plaze0/E-commerce#1]
Great Website! How about adding meta tags in head tho to replace this icon with your sample logo and help you with SEO
![image](https://github.com/0plaze0/E-commerce/assets/80824757/8b2790a1-0c44-40d0-828a-855d397cf99a)

example syntax-
```
<HEAD>
   <meta content="<SITE DESCRIPTION>" property="og:description" />
   <meta content="https://0plaze0.github.io/E-commerce/" property="og:url" />
   <link rel="shortcut icon" type="img/png" href="<YOUR LOGO>">
   <meta content="<RANDOM IMAGE XYZ>" property="og:image" />
   <meta content="#00fffb" data-react-helmet="true" name="theme-color" />
</HEAD>

```

**Comment by 0plaze0** [comment]
Great Idea @Lurku, I would do that

thank you for the suggestion
